### ISSUE TITLE
Lack of Responsiveness

### ISSUE THREAD

**Issue by mitul-garg** [Ayush7-BIT/Tinder_Website_for_dogs#20]
The website looks good on Desktop but the fonts and everything looks small when viewed in mobile.

**Comment by LazyCoder-1506** [comment]
i would like to work on this. please assign to me

**Comment by mitul-garg** [comment]
I would also like to work on this. Please assign it to me also.

**Comment by Ayush7-BIT** [comment]
start working @LazyCoder-1506 @mitul-garg ..

**Comment by mitul-garg** [comment]
Ok, sure!

**Comment by LazyCoder-1506** [comment]
@mitul-garg you carry on with this issue. I don't want to work on it @Ayush7-BIT

**Comment by mitul-garg** [comment]
@LazyCoder-1506 I am also out of it.
@Ayush7-BIT thanks for giving me this opportunity.
