### ISSUE TITLE
Add a favicon to the website.

### ISSUE THREAD

**Issue by dollyjain51099** [Ayush7-BIT/Tinder_Website_for_dogs#21]
Design a logo for the website and place it next to the meta title on the browser tab.

**Comment by dollyjain51099** [comment]
I will be working on this issue, please assign it to me @Ayush7-BIT.

**Comment by Ayush7-BIT** [comment]
start working @dollyjain51099

**Comment by dollyjain51099** [comment]
Yes, I have done and created a PR.
